jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installation
      run:
        |
        python -m pip install --upgrade pip
        pip install cython
        pip install numpy
        python3 setup.py install
        pip install -e .[dev,test]
    - name: Test
      run: pytest
name: nucleus
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, review_requested]

